### ISSUE TITLE
If you don't Scrum you don't work

### ISSUE THREAD

**Issue by colin-higgins** [brettlangdon/theworstprogrammerever#5]
If you don't follow agile to an absolute 't', forget about getting any work done.. It's time for an overhaul.

**Comment by amweiss-pki** [comment]
I feel like I really want this one, let's see if I can get it written this week.

**Comment by amweiss** [comment]
I feel like I really want this one, let's see if I can do it this week.

**Comment by brettlangdon** [comment]
@amweiss go for it!

**Comment by brettlangdon** [comment]
Closed by #9
